export const STROKE_WIDTH = 4
export const HALF_STROKE_WIDTH = STROKE_WIDTH / 2
export const MAX_INITIAL_SIZE = 24 * 16
export const MIN_INITIAL_SIZE = 24 * 8
export const MIN_SIZE = 24 * 2
export const HANDLE_SIZE = 16
export const PADDING = HANDLE_SIZE * 3
export const SEGMENT_COUNT = 12
export const HANDLE_OFFSET = HANDLE_SIZE - STROKE_WIDTH / 2
export const BOX_OFFSET = HANDLE_SIZE * 2 + STROKE_WIDTH * 2
