// Colors from:
// http://museumzero.blogspot.com/2013/09/in-josef-albers-app-colors-interact.html
export const forestGreen = '#3d5041'
export const crimson = '#9f1b35'
export const orange = '#fe3227'
export const salmon = '#cd4560'
export const leaf = '#00a672'
export const teal = '#007990'
export const beige = '#9d9c85'
export const gray = '#8b817f'
export const pink = '#fe8e9b'
export const rust = '#cc7a2a'
export const lime = '#bbd319'
export const pollen = '#e4d700'

export const albers = {
  forestGreen,
  crimson,
  orange,
  salmon,
  leaf,
  teal,
  beige,
  gray,
  pink,
  rust,
  lime,
  pollen
}

export const webColors = [
  'indianred',
  'lightcoral',
  'salmon',
  'darksalmon',
  'lightsalmon',
  'crimson',
  'red',
  'firebrick',
  'darkred',
  'pink',
  'lightpink',
  'hotpink',
  'deeppink',
  'mediumvioletred',
  'palevioletred',
  'lightsalmon',
  'coral',
  'tomato',
  'orangered',
  'darkorange',
  'orange',
  'gold',
  'yellow',
  'lightyellow',
  'lemonchiffon',
  'lightgoldenrodyellow',
  'papayawhip',
  'moccasin',
  'peachpuff',
  'palegoldenrod',
  'khaki',
  'darkkhaki',
  'lavender',
  'thistle',
  'plum',
  'violet',
  'orchid',
  'fuchsia',
  'magenta',
  'mediumorchid',
  'mediumpurple',
  'amethyst',
  'blueviolet',
  'darkviolet',
  'darkorchid',
  'darkmagenta',
  'purple',
  'indigo',
  'slateblue',
  'darkslateblue',
  'mediumslateblue',
  'greenyellow',
  'chartreuse',
  'lawngreen',
  'lime',
  'limegreen',
  'palegreen',
  'lightgreen',
  'mediumspringgreen',
  'springgreen',
  'mediumseagreen',
  'seagreen',
  'forestgreen',
  'green',
  'darkgreen',
  'yellowgreen',
  'olivedrab',
  'olive',
  'darkolivegreen',
  'mediumaquamarine',
  'darkseagreen',
  'lightseagreen',
  'darkcyan',
  'teal',
  'aqua',
  'cyan',
  'lightcyan',
  'paleturquoise',
  'aquamarine',
  'turquoise',
  'mediumturquoise',
  'darkturquoise',
  'cadetblue',
  'steelblue',
  'lightsteelblue',
  'powderblue',
  'lightblue',
  'skyblue',
  'lightskyblue',
  'deepskyblue',
  'dodgerblue',
  'cornflowerblue',
  'mediumslateblue',
  'royalblue',
  'blue',
  'mediumblue',
  'darkblue',
  'navy',
  'midnightblue',
  'cornsilk',
  'blanchedalmond',
  'bisque',
  'navajowhite',
  'wheat',
  'burlywood',
  'tan',
  'rosybrown',
  'sandybrown',
  'goldenrod',
  'darkgoldenrod',
  'peru',
  'chocolate',
  'saddlebrown',
  'sienna',
  'brown',
  'maroon',
  'white',
  'snow',
  'honeydew',
  'mintcream',
  'azure',
  'aliceblue',
  'ghostwhite',
  'whitesmoke',
  'seashell',
  'beige',
  'oldlace',
  'floralwhite',
  'ivory',
  'antiquewhite',
  'linen',
  'lavenderblush',
  'mistyrose',
  'gainsboro',
  'lightgrey',
  'silver',
  'darkgray',
  'gray',
  'dimgray',
  'lightslategray',
  'slategray',
  'darkslategray',
  'black'
]
